[package]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"
name = "bevy_game"
publish = false
version = "0.1.0"

[features]
default = [
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
    "bevy/x11",
    "bevy_kira_audio/ogg",
]
dev = [
    "bevy_editor_pls"
]

[dependencies]
bevy = { version = "0.7", default-features = false }
bevy_ggrs = { version = "0.9.0", features = [ "wasm-bindgen" ] }
matchbox_socket = { version = "0.3.0", features = [ "ggrs-socket" ] }
rand = "0.8.3"
bevy_kira_audio = "0.9"
bevy_asset_loader = "0.10"
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls", optional = true }
ggrs = { version = "0.9.1", features = [ "sync-send", "wasm-bindgen" ] }
bytemuck = { version = "1.9.1", features= [ "derive" ] }
bitflags = "1.3.2"
bevy-web-resizer = "2.0.0"

[target."cfg(target_os = \"linux\")".dependencies.winit]
features = ["x11"]
version = "0.25"


[build-dependencies]
embed-resource = "1.4"

[patch.crates-io]
matchbox_socket = { git = "https://github.com/johanhelsing/matchbox", rev = "b00002da1442396b8ce0babaf6d119c76b33f8d5" }
ggrs = { git = "https://github.com/janhohenheim/ggrs", rev = "9e4a20a6317cfdcff9c352e6f2a37feb33576e54" }
bevy_ggrs = { git = "https://github.com/gschup/bevy_ggrs", rev = "928376df6b37f391ef6593e0355ba5a737ec1492" }


[patch.'https://github.com/gschup/ggrs']

ggrs = { git = "https://github.com/janhohenheim/ggrs", rev = "9e4a20a6317cfdcff9c352e6f2a37feb33576e54" }
